services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-tests
    env_file:
      - .env
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results